config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :comments, only: [ :create, :destroy ]
  get 'comments' => redirect('movies')
  root 'top#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name,          presence: true,   length: { maximum: 50 }
  validates :username,      presence: true,   length: { maximum: 50 },   uniqueness: true
  validates :description,   presence: true,   length: { maximum: 1000 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :description, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to movies_path, notice: "コメントを保存しました。"
    else
      @movies = Movie.order(created_at: :desc)
      render template: "movies/index"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to movies_path, notice: "コメントを削除しました。"
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :movie_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [ :show, :edit, :update, :destroy]
  
  def index
    @movies = Movie.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @movie = Movie.new # フォーム用の空のインスタンスを生成する。
  end

  def create
    @movie = current_user.movies.new(movie_params)
    url = params[:movie][:url]
    url = url.last(11)
    @movie.url = url
    #ここまで

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
    
  end

  def update
    
    if @movie.update(movie_params)
      redirect_to @movie, notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    
    @movie.destroy
    redirect_to movies_path, notice: "投稿を削除しました。"
  end



  private

  def movie_params # ストロングパラメータを定義する
    params.require(:movie).permit(:title)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  
  
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elearning1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    
    
    <div class="main">
      <%= yield %>
    </div>
    
    
    <%= render "shared/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", rows: "7" %>
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control", rows: "7" %>
  </div>



  <p>
    <%= f.submit class: "btn btn-block btn-primary" %>
  </p>
  <p>
    <%= link_to '戻る', :back, class: "btn btn-block btn-dark" %>
  </p>
<% end %>

app/views/movies/edit.html.erb
<div class="row">
  <div class="col-lg-12 mx-auto">
    <div class="logo col-lg-6 mb-3 text-center">
      <h1>編集</h1>
    </div>

    <%# <div class="card"> %>
      <div class="row no-gutters">
        <div class="col-lg-12 mx-auto">
          <% if @movie.url.present? %>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @movie.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <% else %>
            <%= image_tag "no_image", class: "card-img" %>
          <% end %>
        </div>
      </div>
    <%# </div> %>
      <div class="col-lg-6 card-cody">
        <%= render "form", movie: @movie %>
      </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="">
  <div class="col-6 ">

    <% @movies.each do |movie| %>
      <br>
      <%= link_to movie.title, movie %>
      <%# <%= link_to 'Edit', edit_movie_path(movie) %>
      <%# <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= movie.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

      

      <% movie.comments.last(3).each do |comment| %>
        <p>
          <%= comment.user.name %>
          <%= truncate(comment.body, length: 30) %>
          <% if current_user.id == comment.user.id %>
            <%= link_to t(".delete"), comment_path(comment), method: :delete, data: {confirm: '削除してよろしいですか？'} %>
          <% end %>
        </p>
      <% end %>




      <%= form_with model: @comment, url: comments_path, class: "form-group row mx-auto ", local: true do |f| %>
        <%= f.hidden_field :movie_id, value: movie.id %>
        <%= f.text_field :body, class: "col-6 form-control" %>
        <%= f.submit t(".submit"), class: "col-4" %>
      <% end %>
      
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="col-lg-6 mx-auto">
  <div class="logo mb-3 text-center">
    <h1><%= t ".title" %></h1>
  </div>
  <%= render "form", movie: @movie %>
</div>

app/views/movies/show.html.erb
<div class="col-lg-8">
  <div class=>
    <div class="row no-gutters">
      <div class="col-lg-7">
        <div class="">
          <h2>
            <%= simple_format (@movie.title) %>
          </h2>
        </div>
      </div>
      <div class="col-lg-7">
        <% if @movie.url.present? %>
          <iframe width="930" height="520" src="https://www.youtube.com/embed/<%= @movie.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% else %>
          <%= image_tag "no_image", class: "card-img" %>
        <% end %>
        <% @movie.comments.each do |comment| %>
          <p>
            <%= comment.user.name %>
            <%= comment.body %>
          </p>
        <% end %>
      </div>

          <%# <%= form_with model: @comment, url: comments_path, class: "row mx-auto ", local: true do |f| %>
            <%# <%= f.hidden_field :movie_id, value: @movie.id %> 
            <%# <%= f.text_field :body, class: "col-8 form-control" %> 
            <%# <%= f.submit t(".submit"), class: "col-4" %> 
          <%# <% end %> 

    </div>
  </div>
  <p>
    <%= link_to t(".edit"), edit_movie_path(@movie), method: :get, class: "btn btn-block btn-primary" %>
  </p>
  <p>
    <%= button_tag t(".delete"), class: "btn btn-block btn-warning", data: { toggle: "modal", target: "#delete-movie" } %>
  </p>
<div class="modal fade" id="delete-movie">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">投稿削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @movie.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <p><%= "投稿を削除しますか？" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", movie_path(@movie), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<%# <nav class="nav navbar-expand-lg navbar-dark bg-dark fixed-bottom justify-content-center">
  <ul class="nav">
    
    <li class="nav-item">
      <a class="nav-link" href="/"><i class="fas fa-home"></i></a>
    </li>

    <li class="nav-item">
      <%= link_to new_movie_path, class: "nav-link" do %>
        <%# <i class="far fa-plus-square"></i>
      <% end %>
    <%# </li>

    <li class="nav-item">
      <% if user_signed_in? %>
        <%# <%= link_to edit_user_registration_path, class: "nav-link" do %>
          <%# <i class="far fa-user"></i>
        <% end %>
      <%# <% else %>
        <%# <%= link_to new_user_session_path, class: "nav-link" do %>
          <%# <i class="far fa-user"></i> %>
        <%# <% end %>
      <%# <% end %> 
    <%# </li> %>
  <%# </ul> %>
<%# </nav>   %> 

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand font-weight-bold" href="/">eLearning</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      
      <%# <li class="nav-item active">
        <a class="nav-link" href="/">授業を追加する <span class="sr-only">(current)</span></a>
      </li> %>

      <li class="nav-item">
        <%= link_to new_movie_path, class: "nav-link" do %>
          授業を追加する
        <% end %>
      </li>

      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to edit_user_registration_path, class: "nav-link" do %>
            <%# <i class="far fa-user"></i> %>
            プロフィール確認
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <%# <i class="far fa-user"></i> %>
            ログイン
          <% end %>
        <% end %>
      </li>
      
      <%# <li class="nav-item"> %>
        <%# <a class="nav-link" href="#">Link</a> %>
      <%# </li> %>
      
      <%# <li class="nav-item"> %>
        <%# <a class="nav-link disabled" href="#">Disabled</a> %>
      <%# </li> %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/top/index.html.erb
<div class="text-white bg-image sticky-bottom ">
  <h1>Anywhere,anytime,until you're satisfied.</h1>

  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="offset-8">
        <a class="radius_test" href="movies#index">
          動画で学ぶ
        </a>
      </div>
    </div>
  </div> 
  <br>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="offset-8">
        <a class="radius_test" href="movies#index">
          問題で学ぶ
        </a>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="offset-8">
        <a class="radius_test" href="movies#index">
          音声で学ぶ
        </a>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>      